CREATE database BANK;
USE BANK;

-- Admin
-- EmployeeId:7000
-- Pin: 8005


CREATE TABLE Customer (
    ACCNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(45) NOT NULL,
    PHONE BIGINT NOT NULL UNIQUE,
    MAIL VARCHAR(45) UNIQUE,
    BALANCE DECIMAL(12,2) DEFAULT 0.00,
    PIN INT NOT NULL
);

CREATE TABLE Transactions (
    SINO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ACCNO INT,
    AMOUNT DECIMAL(12,2) NOT NULL,
    TRANSACTIONTYPE VARCHAR(45) NOT NULL,
    DATE DATE NOT NULL,
    BALANCE DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (ACCNO) REFERENCES Customer(ACCNO)
);

